### ISSUE TITLE
📚 Maven repositories are not updated 

### ISSUE THREAD

**Issue by zlmr** [appwrite/sdk-for-kotlin#13]
### 💭 Description

Maven repositories are not updated.
- Maven central repository is missing **0.1.1 release**: https://mvnrepository.com/artifact/io.appwrite/sdk-for-kotlin
- Sonatype is missing **0.2.0-SNAPSHOT**: https://s01.oss.sonatype.org/content/repositories/snapshots/io/appwrite/sdk-for-kotlin/

Both those versions are released as per [releases page](https://github.com/appwrite/sdk-for-kotlin/releases) but are not available for use.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Caryntjen** [comment]
Please also add 0.2.1 and 0.2.2:
![image](https://user-images.githubusercontent.com/3481691/148666976-b9f675d2-0874-4eaa-8c75-a58e9b044951.png)

**Comment by christyjacob4** [comment]
@Caryntjen  `0.2.2`  should be available now 🙂

**Comment by Caryntjen** [comment]
@christyjacob4 will the snapshot version 0.2.4-SNAPSHOT also be available on Maven Central?

**Comment by Caryntjen** [comment]
FYI @zlmr the snapshots are available but on a different repo, so I needed to add the following:

```
repositories {
    maven {
        url "https://s01.oss.sonatype.org/content/repositories/snapshots/"
    }
}
```

Thabks @christyjacob4 for the tip!
