### ISSUE TITLE
🐛 Bug Report: Using listCollections and search parameter gives an error 500

### ISSUE THREAD

**Issue by Caryntjen** [appwrite/sdk-for-kotlin#19]
👟 Reproduction steps
I try to retrieve a list of Collection.
Currently I have a collection with NAME: MEMBER and ID: MEMBER . I try to retrieve this collection with the following
`val collectionList = db.listCollections(search = "MEMBER")`

👍 Expected behavior
Get a proper CollectionList object, and a 200 for the call.

👎 Actual Behavior
I get the following errors:
```
Exception in thread "main" io.appwrite.exceptions.AppwriteException: {"message":"Error: Server Error","code":500,"version":"0.12.1"}
	at io.appwrite.Client$awaitResponse$2$1.onResponse(Client.kt:336)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

In appwrite logging I get the following error:
```
[Error] File: /usr/src/code/vendor/utopia-php/framework/src/App.php
[Error] Line: 756
[Error] Type: PDOException
[Error] Message: Can't find FULLTEXT index matching the column list
[Error] File: @swoole-src/library/core/Database/PDOStatementProxy.php
[Error] Line: 64
```

🎲 Appwrite version
Version 0.12.1

💻 Operating system
Windows

🧱 Your Environment
Appwrite v0.12.1 - sdk-for-kotlin v0.2.4
Java v11
Kotlin v1.6.10

👀 Have you spent some time to check if this issue has been raised before?
 I checked and didn't find similar issue
🏢 Have you read the Code of Conduct?
I have read the Code of Conduct

**Comment by Caryntjen** [comment]
(I don't know why but I did not get the bug report template, so I manually added the template)

**Comment by Caryntjen** [comment]
This is also the same issue I have created here: https://github.com/appwrite/sdk-for-kotlin/issues/18 but was already closed. This is now tested on 0.2.4.

Am I doing the wrong call?

**Comment by Caryntjen** [comment]
Still relevant in 0.2.5

**Comment by eldadfux** [comment]
This is not a bug in the SDK, but in Appwrite itself. It was fixed here https://github.com/appwrite/appwrite/pull/2638 and will be available in the next Appwrite release.

**Comment by Caryntjen** [comment]
Okay, thanks @eldadfux !
