### ISSUE TITLE
🐛 Bug Report: Creating of float show Failure status in Appwrite

### ISSUE THREAD

**Issue by Caryntjen** [appwrite/sdk-for-kotlin#20]
👟 Reproduction steps
Succesfully created a float through SDK.
 appwriteDatabase.createFloatAttribute(collectionId = collection.id, key = "key", min = 0.00, required = false, default = 0.00)

👍 Expected behavior
Shows succesful Status in Appwrite Server

👎 Actual Behavior
Shows failure Status in Appwrite Server:

![image](https://user-images.githubusercontent.com/3481691/151718222-0c496ad3-a82b-47d9-a652-2fb2b42ff073.png)

Error in appwrite-worker-database:
`Default value 0 does not match given type double`

🎲 Appwrite version
Version 0.12.1

💻 Operating system
Windows

🧱 Your Environment
Appwrite v0.12.1 - sdk-for-kotlin v0.2.5
Java v11
Kotlin v1.6.10

👀 Have you spent some time to check if this issue has been raised before?
I checked and didn't find similar issue
🏢 Have you read the Code of Conduct?
I have read the Code of Conduct

**Comment by eldadfux** [comment]
Please share the error log for your `appwrite-worker-database` container. In the next release the error information will also be available on the console.

**Comment by Caryntjen** [comment]
@eldadfux updated the description:

Error in appwrite-worker-database:
`Default value 0 does not match given type double`

**Comment by Caryntjen** [comment]
Is there and update on this @eldadfux ?

**Comment by lohanidamodar** [comment]
@TorstenDittmann any update on this?

**Comment by Caryntjen** [comment]
Any idea for solution yet, @TorstenDittmann ?

**Comment by Caryntjen** [comment]
It still applies @TorstenDittmann to version 0.13.0

**Comment by TorstenDittmann** [comment]
Hey, this issue went totally under my radar.

Sorry for the late answer, I'll investigate now 👍

**Comment by Caryntjen** [comment]
@TorstenDittmann is there any progress on finding the issue?

**Comment by Caryntjen** [comment]
@TorstenDittmann @eldadfux any idea in a release date?

**Comment by TorstenDittmann** [comment]
@Caryntjen Found the issue and PR is open for it.

You can expect this to be fixed in the next release, probably around start of next month 👍🏻
