### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by clwater** [appwrite/sdk-for-kotlin#38]
### 👟 Reproduction steps

When I try used Realtime in Kotlin 

### 👍 Expected behavior

but `import io.appwrite.services.Realtime` is error

### 👎 Actual Behavior

I want use this feature

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

io.appwrite:sdk-for-kotlin:5.0.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by abnegate** [comment]
Hi @clwater, this is expected, the realtime service is only available in client-side SDKs. You'll need to use the Android SDK to access it.

**Comment by clwater** [comment]
> Hi @clwater, this is expected, the realtime service is only available in client-side SDKs. You'll need to use the Android SDK to access it.

Thanks for your reply.
If I want listen the appwrete event (like new user register) in my kotlin server. What can i do?

**Comment by abnegate** [comment]
> Thanks for your reply. If I want listen the appwrete event (like new user register) in my kotlin server. What can i do?

@clwater You'd need to proxy the event, the most flexible way would be using an Appwrite Function that triggers on the user create event. If you're willing to do away with the Kotlin server, you could use functions for everything instead

**Comment by clwater** [comment]
Ok, I will try your suggest.
Thanks

**Comment by clwater** [comment]
> > Thanks for your reply. If I want listen the appwrete event (like new user register) in my kotlin server. What can i do?
> 
> @clwater You'd need to proxy the event, the most flexible way would be using an Appwrite Function that triggers on the user create event. If you're willing to do away with the Kotlin server, you could use functions for everything instead

@abnegate  Ok, I will try your suggest.
Thanks
